# Generated by Django 2.2 on 2020-05-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Doctor'),
        ),
    ]
