# Generated by Django 2.2 on 2020-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('First category', 'First category doctor'), ('Second category', 'Second category doctor'), ('Highest category', 'Highest category doctor')], default='First category', max_length=50),
        ),
    ]
