# Generated by Django 2.2 on 2020-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200501_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_image'),
        ),
    ]
